Repository DougieDev/refactor-fitlit-B, pull requests merged in 2020-07, with the labels that each got.

#28 DOM Manipulation Refactor
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: Refactor

#25 Implement user data API #7
  src/data/users.js
  src/images/arnie.jpg
  src/page-manipulation.js
  src/scripts.js
Labels: enhancement

#47 Investigation/jcs/check functions all classes
  src/Activity.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/User.js
Labels: Investigation

#49 more page layout refactoring
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: Refactor

#50 Daily card iterator
  src/Activity.js
  src/Fitlit.js
  src/Hydration.js
  src/Sleep.js
  src/User-repo.js
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: Refactor

#52 Feature/css partials
  src/css/_variables.scss
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
Labels: Sass

#55 Feature/jcs/user user repo function testing
  package-lock.json
  package.json
  src/Activity.js
  src/User-repo.js
  src/User.js
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: Investigation, Refactor, enhancement

#51 Button actions
  src/page-manipulation.js
  src/scripts.js
Labels: enhancement

#57 Data instantiation, Class data structures and new startApp()
  package-lock.json
  src/Activity.js
  src/Hydration.js
  src/Repo.js
  src/Sleep.js
  src/User-repo.js
  src/WellnessMetric.js
  src/scripts.js
Labels: dependencies

#58 Combine Repos
  src/scripts.js
Labels: enhancement

#64 Repo movers
  Old tests/activity-test.js
  Old tests/hydration-test.js
  Old tests/sleep-test.js
  Old tests/user-test.js
  Old tests/userrepo-test.js
  src/Activity.js
  src/ActivityRepo.js
  src/Hydration.js
  src/HydrationRepo.js
  src/Repo.js
  src/Sleep.js
  src/SleepRepo.js
  src/User-repo.js
  src/User.js
  src/UserRepo.js
  src/scripts.js
  test/repo-test.js
  test/scripts-test.js
  test/userrepo-test.js
Labels: Refactor, dependencies

#65 Jcs refacotor inheritance activity
  Old tests/activity-test.js
  src/ActivityRepo.js
  src/HydrationRepo.js
  src/Repo.js
  src/User.js
  src/UserRepo.js
  src/scripts.js
  test/activityrepo-test.js
  test/repo-test.js
Labels: Investigation, Refactor

#66 Data on the DOM
  src/HydrationRepo.js
  src/Repo.js
  src/SleepRepo.js
  src/UserRepo.js
  src/css/_card-design.scss
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: Sass, dependencies, enhancement

#69 Weekly calendar data
  package-lock.json
  src/Repo.js
  src/css/_card-design.scss
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
  test/activityrepo-test.js
  test/repo-test.js
Labels: enhancement

#74 Page navigation / data
  src/UserRepo.js
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: enhancement

#75 DOM manipulation as an object + globals module
  cd
  src/Repo.js
  src/User.js
  src/UserRepo.js
  src/globals.js
  src/page-manipulation.js
  src/scripts.js
Labels: dependencies

#77 Calendar
  .vscode/settings.json
  src/WellnessMetric.js
  src/css/_card-design.scss
  src/data/activity.js
  src/data/hydration.js
  src/data/sleep.js
  src/data/users.js
  src/index.html
  src/page-manipulation.js
  src/scripts.js
Labels: enhancement

#81 Jcs community page
  src/ActivityRepo.js
  src/css/_card-design.scss
  src/css/_media-query.scss
  src/css/_reset.scss
  src/css/_sidebar-design.scss
  src/css/_variables.scss
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  src/scripts.js
  test/activityrepo-test.js
Labels: Sass, enhancement, help wanted

#85 Jcs community display styling
  README.md
  cd
  src/ActivityRepo.js
  src/README.md
  src/UserRepo.js
  src/css/_card-design.scss
  src/css/_media-query.scss
  src/css/_reset.scss
  src/css/_sidebar-design.scss
  src/css/_variables.scss
  src/css/style.scss
  src/index.html
  src/page-manipulation.js
  test/activityrepo-test.js
Labels: Refactor, Sass, documentation, enhancement

#89 PageController Spies
  src/PageController.js
  src/Repo.js
  src/Time.js
  src/User.js
  src/UserRepo.js
  src/css/_card-design.scss
  src/css/_sidebar-design.scss
  src/globals.js
  src/index.html
  src/scripts.js
  test/ActivityRepo.js
  test/PageController-test.js
  test/User-test.js
  test/repo-test.js
  test/scripts-test.js
  test/userrepo-test.js
Labels: Refactor, Spies, documentation, help wanted

#92 Jcs friends card
  project-pics/fitLit mobile.gif
  src/ActivityRepo.js
  src/PageController.js
  src/Time.js
  src/UserRepo.js
  src/css/_card-design.scss
  src/css/_variables.scss
  src/css/style.scss
  src/index.js
  test/PageController-test.js
  test/activity-test.js
  test/userrepo-test.js
Labels: Refactor, Sass, enhancement

#93 Minor styling
  Old tests/hydration-test.js
  src/ActivityRepo.js
  src/PageController.js
  src/Time.js
  src/User.js
  src/UserRepo.js
  src/css/_sidebar-design.scss
  src/css/style.scss
  src/index.html
  src/index.js
  src/scripts.js
  test/PageController-test.js
  test/activity-test.js
Labels: Sass
